name: Build App Launcher for macOS

on:
  workflow_dispatch:
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  build:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build App Launcher (macOS Universal)
        run: npm run build -- --mac --universal

      - name: Rename artifacts
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          cd dist
          # Handle DMG files
          for file in *.dmg; do
            if [[ -f "$file" ]]; then
              mv "$file" "applauncher-${VERSION}-macos-universal.dmg"
            fi
          done
          # Handle ZIP files
          for file in *.zip; do
            if [[ -f "$file" ]]; then
              mv "$file" "applauncher-${VERSION}-macos-unpacked-universal.zip"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: applauncher-macos-universal
          path: |
            dist/applauncher-*.dmg
            dist/applauncher-*.zip
