name: Build App Launcher for All Platforms

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  windows:
    uses: ./.github/workflows/windows.yml
    permissions:
      contents: read
      actions: write

  macos:
    uses: ./.github/workflows/macos.yml
    permissions:
      contents: read
      actions: write

  linux:
    uses: ./.github/workflows/linux.yml
    permissions:
      contents: read
      actions: write

  bundle-artifacts:
    needs: [windows, macos, linux]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Get version from API
        id: get_version
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'package.json'
            });
            const content = Buffer.from(data.content, 'base64').toString();
            const version = JSON.parse(content).version;
            core.setOutput('version', version);

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: applauncher-windows-*
          path: artifacts/windows

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: applauncher-macos-*
          path: artifacts/macos

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: applauncher-linux-*
          path: artifacts/linux

      - name: Create release bundle
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          cd artifacts
          zip -r "../applauncher-${VERSION}-all-platforms.zip" *

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: applauncher-all-platforms
          path: applauncher-*-all-platforms.zip 