name: Build App Launcher for All Platforms

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: ['windows.yml', 'macos.yml', 'linux.yml']
    steps:
      - name: Trigger workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '${{ matrix.workflow }}',
              ref: 'main'
            });
            // Wait a moment to ensure the workflow starts
            await new Promise(resolve => setTimeout(resolve, 5000));
            
            // Get the run ID of the workflow we just triggered
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '${{ matrix.workflow }}',
              branch: 'main',
              per_page: 1
            });
            
            if (runs.data.total_count > 0) {
              const runId = runs.data.workflow_runs[0].id;
              core.setOutput('run-id', runId.toString());
            }

      - name: Wait for workflow to complete
        uses: actions/github-script@v7
        with:
          script: |
            const runId = core.getOutput('run-id');
            if (!runId) {
              throw new Error('No run ID found');
            }
            
            while (true) {
              const { data: run } = await github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: parseInt(runId)
              });
              
              if (run.status === 'completed') {
                if (run.conclusion !== 'success') {
                  throw new Error(`Workflow failed with conclusion: ${run.conclusion}`);
                }
                break;
              }
              
              console.log('Waiting for workflow to complete...');
              await new Promise(resolve => setTimeout(resolve, 10000));
            }

  bundle-artifacts:
    needs: trigger-builds
    runs-on: ubuntu-latest
    steps:
      - name: Get version from API
        id: get_version
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'package.json'
            });
            const content = Buffer.from(data.content, 'base64').toString();
            const version = JSON.parse(content).version;
            core.setOutput('version', version);

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: applauncher-windows-*
          path: artifacts/windows

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: applauncher-macos-*
          path: artifacts/macos

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: applauncher-linux-*
          path: artifacts/linux

      - name: Create release bundle
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          cd artifacts
          zip -r "../applauncher-${VERSION}-all-platforms.zip" *

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: applauncher-all-platforms
          path: applauncher-*-all-platforms.zip 