name: Build App Launcher for Windows

on:
  workflow_dispatch:  # Manual trigger only
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Download 7-Zip CLI
        shell: pwsh
        run: |
          $url = "https://www.7-zip.org/a/7za920.zip"
          Invoke-WebRequest -Uri $url -OutFile "7za.zip"
          Expand-Archive "7za.zip" -DestinationPath "7za"
          echo "${{ github.workspace }}\7za" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        shell: pwsh
        run: |
          $VERSION = (node -p "require('./package.json').version")
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT

      - name: Build App Launcher (Windows x64)
        run: npm run build -- --win --x64

      - name: Create x64 ZIP with 7-Zip
        shell: pwsh
        run: |
          $VERSION = "${{ steps.get_version.outputs.version }}"
          cd dist/win-unpacked
          7za a -tzip -mx=9 "../applauncher-${VERSION}-windows-unpacked-x64.zip" *
          cd ../..

      - name: Rename and clean x64 artifacts
        shell: pwsh
        run: |
          $VERSION = "${{ steps.get_version.outputs.version }}"
          # Handle EXE files
          Get-ChildItem -Path "dist" -Filter "*.exe" | ForEach-Object {
            Move-Item $_.FullName "dist/applauncher-${VERSION}-windows-x64.exe"
          }
          Remove-Item -Path "dist/win-unpacked" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Upload x64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: applauncher-windows-x64
          path: |
            dist/applauncher-*-windows-x64.exe
            dist/applauncher-*-windows-unpacked-x64.zip

      - name: Clean dist folder before x86 build
        shell: pwsh
        run: Remove-Item -Path "dist/*" -Recurse -Force

      - name: Build App Launcher (Windows x86)
        run: npm run build -- --win --ia32

      - name: Create x86 ZIP with 7-Zip
        shell: pwsh
        run: |
          $VERSION = "${{ steps.get_version.outputs.version }}"
          cd dist/win-ia32-unpacked
          7za a -tzip -mx=9 "../applauncher-${VERSION}-windows-unpacked-x86.zip" *
          cd ../..

      - name: Rename and clean x86 artifacts
        shell: pwsh
        run: |
          $VERSION = "${{ steps.get_version.outputs.version }}"
          # Handle EXE files
          Get-ChildItem -Path "dist" -Filter "*.exe" | ForEach-Object {
            Move-Item $_.FullName "dist/applauncher-${VERSION}-windows-x86.exe"
          }
          Remove-Item -Path "dist/win-unpacked" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Upload x86 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: applauncher-windows-x86
          path: |
            dist/applauncher-*-windows-x86.exe
            dist/applauncher-*-windows-unpacked-x86.zip

      - name: Clean dist folder before ARM64 build
        shell: pwsh
        run: Remove-Item -Path "dist/*" -Recurse -Force

      - name: Build App Launcher (Windows ARM64)
        run: npm run build -- --win --arm64

      - name: Create ARM64 ZIP with 7-Zip
        shell: pwsh
        run: |
          $VERSION = "${{ steps.get_version.outputs.version }}"
          cd dist/win-arm64-unpacked
          7za a -tzip -mx=9 "../applauncher-${VERSION}-windows-unpacked-arm64.zip" *
          cd ../..

      - name: Rename and clean ARM64 artifacts
        shell: pwsh
        run: |
          $VERSION = "${{ steps.get_version.outputs.version }}"
          # Handle EXE files
          Get-ChildItem -Path "dist" -Filter "*.exe" | ForEach-Object {
            Move-Item $_.FullName "dist/applauncher-${VERSION}-windows-arm64.exe"
          }
          Remove-Item -Path "dist/win-unpacked" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Upload ARM64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: applauncher-windows-arm64
          path: |
            dist/applauncher-*-windows-arm64.exe
            dist/applauncher-*-windows-unpacked-arm64.zip